### ISSUE TITLE
NoSuchMethodError from SwaggerSupport

### ISSUE THREAD

**Issue by danxmoran** [http4s/rho#291]
Using:
* http4s 0.20.0-M5
* rho 0.19.0-M5

I'm able to compile simple route definitions, but when I try to run my app I get a `NoSuchMethodError` generating the Swagger routes. The full stack trace is:
```
[error] java.lang.NoSuchMethodError: org.http4s.rho.swagger.SwaggerSupport$$anon$1.instance(Lcats/Monad;Lshapeless/ops/function$FnToProduct;Lshapeless/ops/hlist$Reverse;Lorg/http4s/rho/bits/ResultMatcher;)Lorg/http4s/rho/bits/HListToFunc;
[error]         at org.http4s.rho.swagger.SwaggerSupport$$anon$1.<init>(SwaggerSupport.scala:97)
[error]         at org.http4s.rho.swagger.SwaggerSupport.createSwaggerRoute(SwaggerSupport.scala:83)
[error]         at org.http4s.rho.swagger.SwaggerSupport.swaggerRoute$lzycompute$1(SwaggerSupport.scala:43)
[error]         at org.http4s.rho.swagger.SwaggerSupport.swaggerRoute$1(SwaggerSupport.scala:42)
[error]         at org.http4s.rho.swagger.SwaggerSupport.$anonfun$createRhoMiddleware$1(SwaggerSupport.scala:45)
[error]         at org.http4s.rho.RoutesBuilder.toRoutes(RoutesBuilder.scala:17)
[error]         at org.http4s.rho.RhoRoutes.toRoutes(RhoRoutes.scala:50)
[error]         at org.broadinstitute.transporter.api.ManagerApi.routes(ManagerApi.scala:44)
[error]         at org.broadinstitute.transporter.TransporterManager$.$anonfun$bindAndRun$1(TransporterManager.scala:40)
[error]         at cats.effect.Resource.$anonfun$use$1(Resource.scala:119)
[error]         at cats.effect.internals.IOBracket$BracketStart.liftedTree1$1(IOBracket.scala:79)
[error]         at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:79)
[error]         at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
[error]         at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
[error]         at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
[error]         at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
[error]         at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
[error]         at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
[error]         at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
[error]         at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:72)
[error]         at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:52)
[error]         at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
[error]         at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
[error]         at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:44)
[error]         at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:34)
[error]         at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:337)
[error]         at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:119)
[error]         at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:351)
[error]         at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:372)
[error]         at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
[error]         at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
[error]         at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[error]         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error]         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error]         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error]         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I haven't been able to minimize the problem, but my WIP code is [here](https://github.com/DataBiosphere/transporter/tree/dm-transporter-status-version-DSPDC-175).

**Comment by danxmoran** [comment]
🤦‍♂️ nevermind, I'd somehow gotten my local caches into a bad state. Wiping everything fixed the problem.

**Comment by zarthross** [comment]
Does sbt provide any eviction warnings?
