### ISSUE TITLE
Got Error with http4s-scala-xml

### ISSUE THREAD

**Issue by xiongchenyu6** [http4s/rho#367]
Scala : 2.13.1
rho : 0.20.0-M1
http4s: 0.21.0-M5
http4s-scala-xml: 0.21.0-M5

I am trying to build a web service and support CAS login, I need to decode some XML from the request body. So I use the http4s-scala-xml 0.21.0-M5 to provide the Entity Decoder, here is the route : 
``` scala

  "For checking cas logout" **
    GET / "event" / "logout" ^ EntityDecoder[F, Elem] |>> { (elem: Elem) =>
    elem match {
      case <samlp:LogoutRequest><saml:NameID>{nameID}</saml:NameID><samlp:SessionIndex>{ticket}</samlp:SessionIndex></samlp:LogoutRequest> =>
        Some(ticket.text)
      case _ => None
    }
    Ok("")
  }
```

And get error at runtime

```
root java.util.NoSuchElementException: head of empty list
root    at scala.collection.immutable.Nil$.head(List.scala:592)
root    at scala.collection.immutable.Nil$.head(List.scala:591)
root    at org.http4s.rho.swagger.SwaggerModelsBuilder.mkBodyParam(SwaggerModelsBuilder.scala:291)
root    at org.http4s.rho.swagger.SwaggerModelsBuilder.collectBodyParams(SwaggerModelsBuilder.scala:127)
root    at org.http4s.rho.swagger.SwaggerModelsBuilder.collectOperationParams(SwaggerModelsBuilder.scala:203)
root    at org.http4s.rho.swagger.SwaggerModelsBuilder.mkOperation(SwaggerModelsBuilder.scala:259)
root    at org.http4s.rho.swagger.SwaggerModelsBuilder.$anonfun$collectPaths$1(SwaggerModelsBuilder.scala:30)
root    at scala.collection.immutable.List.map(List.scala:219)
root    at org.http4s.rho.swagger.SwaggerModelsBuilder.collectPaths(SwaggerModelsBuilder.scala:29)
root    at org.http4s.rho.swagger.SwaggerModelsBuilder.mkSwagger(SwaggerModelsBuilder.scala:25)
root    at org.http4s.rho.swagger.SwaggerSupport.$anonfun$createSwagger$1(SwaggerSupport.scala:66)
root    at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:636)
root    at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:632)
root    at scala.collection.AbstractIterable.foldLeft(Iterable.scala:921)
root    at org.http4s.rho.swagger.SwaggerSupport.createSwagger(SwaggerSupport.scala:66)
root    at org.http4s.rho.swagger.SwaggerSupport.swaggerSpec$lzycompute$1(SwaggerSupport.scala:41)
root    at org.http4s.rho.swagger.SwaggerSupport.swaggerSpec$1(SwaggerSupport.scala:39)
root    at org.http4s.rho.swagger.SwaggerSupport.$anonfun$createRhoMiddleware$2(SwaggerSupport.scala:45)
root    at org.http4s.rho.swagger.SwaggerSupport$$anon$2.response$lzycompute(SwaggerSupport.scala:91)
root    at org.http4s.rho.swagger.SwaggerSupport$$anon$2.response(SwaggerSupport.scala:87)
root    at org.http4s.rho.swagger.SwaggerSupport$$anon$2.$anonfun$new$1(SwaggerSupport.scala:99)
root    at shapeless.ops.FnToProductInstances$$anon$1.$anonfun$apply$1(fntoproduct.scala:37)
root    at org.http4s.rho.bits.MatchersHListToFunc$$anon$2.$anonfun$conv$2(HListToFunc.scala:35)
root    at org.http4s.rho.bits.PathTreeOps.$anonfun$makeLeaf$2(PathTree.scala:93)
root    at org.http4s.rho.bits.ResultResponse.map(ResultResponse.scala:35)
root    at org.http4s.rho.bits.ResultResponse.map$(ResultResponse.scala:34)
root    at org.http4s.rho.bits.SuccessResponse.map(ResultResponse.scala:51)
root    at org.http4s.rho.bits.PathTreeOps.$anonfun$makeLeaf$1(PathTree.scala:92)
root    at org.http4s.rho.bits.PathTreeOps$SingleLeaf.attempt(PathTree.scala:133)
root    at org.http4s.rho.bits.PathTreeOps$Node.walkNil$1(PathTree.scala:255)
root    at org.http4s.rho.bits.PathTreeOps$Node.walk(PathTree.scala:273)
root    at org.http4s.rho.bits.PathTreeOps$Node.walk$(PathTree.scala:220)
root    at org.http4s.rho.bits.PathTreeOps$MatchNode.walk(PathTree.scala:278)
root    at org.http4s.rho.bits.PathTreeOps$Node.walkHeadTail$1(PathTree.scala:229)
root    at org.http4s.rho.bits.PathTreeOps$Node.walk(PathTree.scala:272)
root    at org.http4s.rho.bits.PathTreeOps$Node.walk$(PathTree.scala:220)
root    at org.http4s.rho.bits.PathTreeOps$MatchNode.walk(PathTree.scala:278)
root    at org.http4s.rho.bits.PathTreeOps$Node.walkTree(PathTree.scala:216)
root    at org.http4s.rho.bits.PathTreeOps$Node.walkTree$(PathTree.scala:214)
root    at org.http4s.rho.bits.PathTreeOps$MatchNode.walkTree(PathTree.scala:278)
root    at org.http4s.rho.bits.PathTreeOps$PathTree.getResult(PathTree.scala:78)
root    at org.http4s.rho.CompileRoutes$.$anonfun$foldRoutes$2(CompileRoutes.scala:45)
root    at org.http4s.Http$.$anonfun$apply$2(Http.scala:20)
root    at cats.effect.Sync$OptionTSync.$anonfun$suspend$2(Sync.scala:202)
root    at cats.effect.internals.IORunLoop$.liftedTree1$1(IORunLoop.scala:95)
root    at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:95)
root    at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
root    at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:86)
root    at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
root    at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
root    at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
root    at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
root    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
root    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
root    at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
root    at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
root    at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
root    at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:72)
root    at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:52)
root    at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
root    at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
root    at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:44)
root    at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:34)
root    at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:341)
root    at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:119)
root    at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
root    at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
root    at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
root    at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
root    at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:51)
root    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
root    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
root    at java.lang.Thread.run(Thread.java:748)

**Comment by xiongchenyu6** [comment]
I guess *rho* just works on the `case class` Since Elem is a `class`. I think this is the desired behavior. Is there any way to work around it? Thanks.

**Comment by zarthross** [comment]
When you go to generate the swagger routes, you can set some default swagger formats, you could try writing your own swagger format for `Elem`.

See [here](https://github.com/http4s/rho/blob/73b8e7c1bb5694298ffaaa2478b7b3cd6d7f3350/swagger/src/main/scala/org/http4s/rho/swagger/SwaggerSupport.scala#L26) and https://github.com/http4s/rho/blob/master/swagger/src/main/scala/org/http4s/rho/swagger/SwaggerFormats.scala in rho

and and example (maybe outdated) [here](https://github.com/http4s/rho/blob/d49234f7de284485175617ad9a82cb807b678aca/Rho.md)
