### ISSUE TITLE
NoSuchMethodError from rho 0.20.0-M1

### ISSUE THREAD

**Issue by Ray-Eldath** [http4s/rho#371]
After a day's debug still don't work, pretty frustrating...

Dependencies:
 -   `"org.http4s" %% "rho-swagger" % "0.20.0-M1"`
 -   `"org.http4s" %% "http4s-blaze-server" % "0.21.0-M6"`
 -   `"org.typelevel" %% "cats-effect" % "2.0.0"`

Using Scala `2.13.1`.

It's ok to compile my simple route app, but when run it throw a `NoSuchMethodError`:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'cats.data.Kleisli org.http4s.HttpRoutes$.apply(scala.Function1, cats.effect.Sync)'
	at org.http4s.rho.CompileRoutes$.foldRoutes(CompileRoutes.scala:45)
	at org.http4s.rho.RoutesBuilder.toRoutes(RoutesBuilder.scala:20)
	at org.http4s.rho.RhoRoutes.toRoutes(RhoRoutes.scala:51)
	at ray.eldath.scala.learning.rest.Rho$.run(Rho.scala:26)
	at cats.effect.IOApp.$anonfun$main$3(IOApp.scala:67)
	at cats.effect.internals.IOAppPlatform$.mainFiber(IOAppPlatform.scala:37)
	at cats.effect.internals.IOAppPlatform$.main(IOAppPlatform.scala:24)
	at cats.effect.IOApp.main(IOApp.scala:67)
	at cats.effect.IOApp.main$(IOApp.scala:66)
	at ray.eldath.scala.learning.rest.Rho$.main(Rho.scala:10)
	at ray.eldath.scala.learning.rest.Rho.main(Rho.scala)
```

and the code is on [GitHub Gists](https://gist.github.com/Ray-Eldath/77f1b164ada9c09ddb83105eccfc69c0).

BTW, I think there's only few documents and example to show how to construct an app... Hope could be better soon.

**Comment by zarthross** [comment]
I apologize for the frustration, but you are using Http4s M6 but the version of Rho you are using is compiled against M5, we can't guarantee binary compatibility for milestone releases (see [here](https://github.com/http4s/rho/wiki/Versions)).

I'll try to get a version compiled against M6 released soon.

**Comment by Ray-Eldath** [comment]
Apologize for not read the document you mentioned... I downgrade to `0.21.0-M5` and it works fine now.

Many thx.
